SpaceInvadersNoFrameskip-v4:
  env_wrapper:
    - stable_baselines3.common.atari_wrappers.AtariWrapper
  frame_stack: 4
  policy: CnnPolicy
  n_timesteps: 2e6
  buffer_size: 1000000
  learning_rate: 1e-4
  batch_size: 32
  learning_starts: 100000
  train_freq: 4
  gradient_steps: 1
  target_update_interval: 1000
  exploration_fraction: 0.2
  exploration_final_eps: 0.05
  double_q: True
  policy_kwargs:
    dueling: True,
    features_extractor_kwargs:
        cnn_arch:
          - [32, 8, 4]
          - [64, 4, 2]
          - [64, 3, 1]
          - [128, 3, 1]
